# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.17.0-beta.3
maven_group = cc.cassian
archives_name = pyrite
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1
yarn_mappings_build = 3

# Dependencies
architectury_api_version = 13.0.6
fabric_loader_version = 0.16.14
fabric_api_version = 0.116.4
neoforge_version = 21.1.148
yarn_mappings_patch_neoforge_version = 1.21+build.4

# Compatibility Dependencies
aether_version = 1.5.1-beta.4
emi_version = 1.1.18
columns_version = 1.10.0
chest_variants_version = 1.5.6+1.21
quad_version = 1.2.9+1.21.1
fdrf_version = 1.21.1-3.1.2+refabricated
kaleido_version=0.3.3+1.3.2
mcqoy_version=adCKjC4q
cloth_version=15.0.127
modmenu_version = 11.0.1
totally_lit_version = 1.1.1+1.21.1
owo_version = 0.12.15.4+1.21

# Publishing
modrinth_id = qO4ozPoe
curseforge_id = 1101500