# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.16.1-beta.1
maven_group = cc.cassian
archives_name = pyrite
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.5
yarn_mappings_build = 1

# Dependencies
architectury_api_version = 14.0.4
fabric_loader_version = 0.16.14
fabric_api_version = 0.128.1
neoforge_version = 21.5.87
yarn_mappings_patch_neoforge_version = 1.21+build.4

# Compatibility Dependencies
aether_version = 1.5.1-beta.4
eiv_version = 2.5.3+1.21.5
columns_version = 1.12.0
chest_variants_version = 1.5.12+1.21.5
quad_version = 1.2.13+1.21.5
fdrf_version = 1.21.5-3.2.4+refabricated

# Publishing
modrinth_id = qO4ozPoe
curseforge_id = 1101500