# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.16.0
maven_group = cc.cassian
archives_name = pyrite
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1
yarn_mappings_build = 3

# Dependencies
architectury_api_version = 13.0.6
fabric_loader_version = 0.16.9
fabric_api_version = 0.107.0
neoforge_version = 21.1.148
yarn_mappings_patch_neoforge_version = 1.21+build.4

# Compatibility Dependencies
aether_version = 1.5.1-beta.4
emi_version = 1.1.18
columns_version = 1.10.0
chest_variants_version = 1.5.6+1.21
quad_version = 1.2.9+1.21.1

# Publishing
modrinth_id = qO4ozPoe
curseforge_id = 1101500