deps.minecraft=1.21.1
deps.neoforge=21.1.219
deps.parchment=1.21.1:2024.11.17

mod.mc_dep_forgelike=[1.21.1, 1.21.2)

deps.yacl = 3.7.1+1.21.1
deps.cloth_config = 19.0.147
deps.item_descriptions = 2.7.0+1.21.1
deps.aether = 1.5.1-beta.4
deps.emi = 1.1.18
deps.lolmcv = 1.5.15+1.21.1
deps.quad = 1.2.9+1.21.1
deps.fd = opCbq7uB
deps.copper_age_backport = JEPUV1lF
deps.terraform_wood_api=11.0.0-neoforge