deps.minecraft=1.21.10
deps.fabric-api=0.135.0+1.21.10
deps.parchment=1.21.10:2025.10.12

mod.mc_dep_fabric=~1.21.9
publish.additionalVersions=1.21.9

deps.yacl = 3.8.0+1.21.9
deps.modmenu = 16.0.0-rc.1
deps.item_descriptions = 2.5.8+1.21.10
deps.cloth_config = 20.0.149
deps.eiv = 5.1.0+1.21.10
deps.columns = 1.12.0
deps.lolmcv = 1.5.14+1.21.10
deps.quad = 1.2.14+1.21.9
deps.fdrf = 1.21.10-3.3.3+refabricated
deps.totally_lit = 1.1.1+1.21.1