deps.minecraft=1.21.8
deps.fabric-api=0.136.0+1.21.8
deps.parchment=1.21.8:2025.09.14

mod.mc_dep_fabric=>=1.21.6 <1.21.9
publish.additionalVersions=1.21.7

deps.yacl = 3.7.1+1.21.6
deps.modmenu = 15.0.0
deps.cloth_config = 19.0.147
deps.aether = 1.5.1-beta.4
deps.emi = 1.1.18
deps.eiv = 4.1.0+1.21.8
deps.columns = 1.12.0
deps.lolmcv = 1.5.14+1.21.8
deps.quad = 1.2.14+1.21.8
deps.fdrf = 1.21.8-3.3.2+refabricated
deps.totally_lit = 1.1.1+1.21.1