deps.minecraft=26.3
deps.fabric-api=0.160.4+26.3

mod.mc_dep_fabric=>26.2 <26.4

deps.yacl = 3.9.6+26.3
deps.modmenu = 21.0.0-alpha.1
deps.item_descriptions = 2.7.7+26.2-pre-6
deps.rrv = 8.10.4+26.3-pre-1
deps.columns = 1.12.0
deps.fd = 26.3-3.6.21
deps.mcqoy=0.4.1+fabric-26.1
deps.totally_lit = 1.1.1+1.21.1
deps.lolmcv=1.5.14+26.1.1-Fabric
deps.quad=1.2.15+26.1-Fabric