deps.minecraft=1.21.10
deps.neoforge=21.10.16-beta
deps.parchment=1.21.10:2025.10.12

mod.mc_dep_forgelike=[1.21.9, 1.21.11]
publish.additionalVersions=1.21.9

deps.yacl = 3.8.0+1.21.9
deps.cloth_config = 20.0.149
deps.aether = 1.5.1-beta.4
deps.emi = 1.1.18
deps.eiv = 5.1.0+1.21.10
deps.lolmcv = 1.5.14+1.21.8
deps.quad = 1.2.14+1.21.9
deps.fd = opCbq7uB