deps.minecraft=26.1-snapshot-4
deps.fabric-api=0.142.1+26.1

mod.mc_dep_fabric=>1.21.11

deps.yacl = 3.8.2+26.1.0
deps.modmenu = 18.0.0-alpha.4
deps.item_descriptions = 2.6.1+26.1
deps.rrv = 6.3.2+26.1-snapshot-4
deps.columns = 1.12.0
deps.lolmcv = 1.5.14+1.21.10
deps.quad = 1.2.14+1.21.9
deps.fd = opCbq7uB
deps.totally_lit = 1.1.1+1.21.1